"""rename tasks_json to tasks

Revision ID: 6fcc3a8d5df6
Revises: ce520b826ef9
Create Date: 2025-10-05 13:10:38.218961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fcc3a8d5df6'
down_revision: Union[str, Sequence[str], None] = 'ce520b826ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tasklist', sa.Column('tasks', sa.JSON(), nullable=False))
    # op.drop_column('tasklist', 'tasks_json')
    # ### end Alembic commands ###
    op.alter_column('tasklist', 'tasks_json', new_column_name='tasks')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tasklist', sa.Column('tasks_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # op.drop_column('tasklist', 'tasks')
    # ### end Alembic commands ###
    op.alter_column('tasklist', 'tasks', new_column_name='tasks_json')
