"""update tasklist table

Revision ID: d2d10915d949
Revises: 9ab68e044ccb
Create Date: 2025-10-04 19:04:01.982568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd2d10915d949'
down_revision: Union[str, Sequence[str], None] = '9ab68e044ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'tasklist', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasklist', type_='unique')
    op.drop_column('tasklist', 'title')
    # ### end Alembic commands ###
